S2B/Controllers/FucionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using S2B.Models;

namespace S2B.Controllers
{
    public class FucionariosController : Controller
    {
        private bd_projeto_data db = new bd_projeto_data();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            HttpCookie Login_User = Request.Cookies["Login"];
            HttpCookie Login_Senha = Request.Cookies["Senha"];
            if (Login_User != null && Login_Senha != null)
            {
                string senha = Login_Senha.Value;
                string user = Login_User.Value;
                if (!(db.FUNCIONARIOs.Where(a => a.LOGIN.Equals(user) && a.SENHA.Equals(senha)).Count() == 1))
                {
                    Response.Redirect("/Home/Login");
                }
            }
            else
            {
                Response.Redirect("/Home/Login");
            }
        }

        // GET: Fucionarios
        public async Task<ActionResult> Index()
        {
            return View(await db.FUNCIONARIOs.ToListAsync());
        }

        // GET: Fucionarios/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FUNCIONARIO fUNCIONARIO = await db.FUNCIONARIOs.FindAsync(id);
            if (fUNCIONARIO == null)
            {
                return HttpNotFound();
            }
            return View(fUNCIONARIO);
        }

        // GET: Fucionarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fucionarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "COD_FUNCIONARIO,NOME,CPF,LOGIN,SENHA,EMAIL,ENDERECO,TELEFONE,CELULAR,TIPO")] FUNCIONARIO fUNCIONARIO)
        {
            if (ModelState.IsValid)
            {
                db.FUNCIONARIOs.Add(fUNCIONARIO);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(fUNCIONARIO);
        }

        // GET: Fucionarios/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FUNCIONARIO fUNCIONARIO = await db.FUNCIONARIOs.FindAsync(id);
            if (fUNCIONARIO == null)
            {
                return HttpNotFound();
            }
            return View(fUNCIONARIO);
        }

        // POST: Fucionarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "COD_FUNCIONARIO,NOME,CPF,LOGIN,SENHA,EMAIL,ENDERECO,TELEFONE,CELULAR,TIPO")] FUNCIONARIO fUNCIONARIO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fUNCIONARIO).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(fUNCIONARIO);
        }

        // GET: Fucionarios/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FUNCIONARIO fUNCIONARIO = await db.FUNCIONARIOs.FindAsync(id);
            if (fUNCIONARIO == null)
            {
                return HttpNotFound();
            }
            return View(fUNCIONARIO);
        }

        // POST: Fucionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            FUNCIONARIO fUNCIONARIO = await db.FUNCIONARIOs.FindAsync(id);
            db.FUNCIONARIOs.Remove(fUNCIONARIO);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

S2B/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Piezime | @ViewBag.Title  </title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Styles/css")
    @Scripts.Render("~/bundles/modernizr")
    @using S2B.Models;
</head>
<body data-spy="scroll" data-target="#topnav">
    <div class="navbar navbar-color navbar-fixed-top" id="topnav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-reorder"></span>
                </button>
                @Html.ActionLink("Piezime", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        bd_projeto_data db = new bd_projeto_data();//Connecta ao banco
                        HttpCookie Login_User = Request.Cookies["Login"];
                        HttpCookie Login_Senha = Request.Cookies["Senha"];

                        if (Login_User != null && Login_Senha != null)
                        {
                            string senha = Login_Senha.Value;
                            string user = Login_User.Value;
                            if ((db.FUNCIONARIOs.Where(a => a.LOGIN.Equals(user) && a.SENHA.Equals(senha)).Count() == 1))
                            {
                                <li>@Html.ActionLink("Funcionarios", "Index", "Fucionarios")</li>
                                <li>@Html.ActionLink("Produtos", "Index", "Produtos")</li>
                                <li>@Html.ActionLink("Vendas", "Index", "Vendas")</li>
                                <li>@Html.ActionLink("Sair", "Sair", "Home")</li>
                            }
                        }
                        else
                        {
                            <li>@Html.ActionLink("Log In", "Login", "Home")</li>
                        }
                    }
                </ul>
            </div>
            <!--/.navbar-collapse -->
        </div>
    </div>

    @RenderBody()
    <hr />

    <footer id="footer">
        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-2">
                        <a class="logo" href="index.html">
                            <img src="~/Styles/images/logo-footer.png" alt="Template Eden">
                        </a>
                    </div>
                    <div class="col-md-5">
                        <p>&copy; Copyright 2013 by 5-S2B-Team. All Rights Reserved.</p>
                    </div>
                    <div class="col-md-5">
                        <nav id="footer-menu">
                            <ul>
                                <li><a href="#">FAQ's</a></li>
                                <li><a href="#">Sitemap</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(function () {
            if ($(window).width() > 960) {
                var tw = $('.triangles').width() / 7 + 32;
                var ta = tw / 2 + 22;
                $('.down-triangle').css('border-top', tw + 'px solid rgba(0,0,0,0.8)').css('border-left', ta + 'px solid transparent').css('border-right', ta + 'px solid transparent');
                $('.up-triangle').css('border-bottom', tw + 'px solid rgba(0,0,0,0.8)').css('border-left', ta + 'px solid transparent').css('border-right', ta + 'px solid transparent');
            }
            $('#wd-wrapper').sinusoid({
                minImgW: 80,
                maxImgW: 130,
                minImgAngle: -20,
                maxImgAngle: 20,
                leftFactor: 60,
                sinusoidFunction: {
                    A: 70,
                    T: 1700,
                    P: 0
                }
            });


            $('a[href*=#]:not([href=#]):not([rel=crs])').click(function () {
                if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
                    var target = $(this.hash);
                    target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                    if (target.length) {
                        $('html,body').animate({
                            scrollTop: target.offset().top
                        }, 1000);
                        return false;
                    }
                }
            });

        });
    </script>
</body>
</html>